### ISSUE TITLE
Letters disappear in some seconds

### ISSUE THREAD

**Issue by Cjaker** [rds1983/SpriteFontPlus#20] opened 2020-01-10 09:17 UTC
Hello!
I'm using DynamicFont and after some seconds the word 'Teste' disappears the letter and left just 'T' at my text, what can be? (starts by 'Teste', after 15 seconds +- disappear and after some time he show 'Teste' again)

![Screenshot_1](https://user-images.githubusercontent.com/20959344/72141082-e801b080-3370-11ea-8bd6-27b16cc6a16b.png)
![Screenshot_2](https://user-images.githubusercontent.com/20959344/72141085-e9cb7400-3370-11ea-9059-5eb6ad190b57.png)

**Comment by rds1983** [comment] 2020-01-10 12:58
No idea. Can you provide a sample code that reproduces the problem?

**Comment by Eternal-Scripts** [comment] 2020-01-11 18:44
Yes! I'm using Vecna otf converted to ttf.
I'm initializing the font object like this.
`Font.DefaultUiFont = DynamicSpriteFont.FromTtf(File.ReadAllBytes(@"Vecna.ttf"), 20);`

And when i will draw i just change the size avoiding alloc dynamicspritefont for every label, maybe is this?

`label.DynamicFont.Size = label.TextSize;
Core.SpriteBatch.DrawString(label.DynamicFont, label.Text, label.GetDrawPos(), label.Color);`

**Comment by dmanning23** [comment] 2020-01-30 18:10
I've been using SpriteFontPlus on a few different platforms, and I've seen this on WindowsDX projects. I haven't seen this on Android or iOS.

**Comment by rds1983** [comment] 2020-01-30 18:30
Well, I can't reproduce it with stock samples neither with MonoGame.DesktopGL neither with MonoGame.WindowsDX.
So I would need complete sample project that has this issue.

**Comment by rds1983** [comment] 2020-10-15 21:27
Closing since DynamicSpriteFont had been moved to the new project: https://github.com/rds1983/FontStashXNA
Feel free to reopen the issue there.

**Closed by rds1983** 2020-10-15 21:27 UTC
